### PR TITLE
updated scala.js and a couple of other dependencies.

### PR DESCRIPTION
**Pull request by kailuowang**

### CODE REVIEW

**Comment by BennyHill** [comment]
Looks like an extra import is needed. See breaking at https://www.scala-js.org/news/2018/05/22/announcing-scalajs-0.6.23/

**Comment by BennyHill** [comment]
Ahh... Its worse. Need to use portable scala as well, I think. I can look over weekend if still open

**Comment by BennyHill** [comment]
Ok, we have scheduled the larger change.

So :+1:

**Comment by kailuowang** [comment]
cool , thanks @BennyHill when I get time I would work on migrating to portable scala too, but my schedule in the following days are pretty hectic...

**Pull request merged**
