### PR TITLE
Bring all referenced deps as test dependencies

### PR DESCRIPTION
**Pull request by kailuowang**
Now the version numbers are tested on CI. Hopefully @scala-steward will pick them up as well, although the numbers are in [src/main/scala/](https://github.com/typelevel/sbt-catalysts/blob/master/src/main/scala/org/typelevel/TypelevelDeps.scala) so not sure if it can still find them. 

Update: it seems to me, after a quick glance of scala-steward code,  that scala-steward search the entire repo.

### CODE REVIEW

**Comment by fthomas** [comment]
@scala-steward will look for version numbers in all `.scala` and `.sbt` files, so it won't have problems finding them in src/main/scala.

If you want to, I can run Scala Steward just on this repo to give you rapid feedback. It just needs this PR to be merged before running.

**Comment by kailuowang** [comment]
@fthomas thanks! although there is no need to manually run. I updated all the deps in this PR, so scala-steward won't have anything to do.

**Comment by fthomas** [comment]
I'm curious now and running it anyway. :-)

**Comment by kailuowang** [comment]
@fthomas ha I missed a few,
```
 human : algorithm 
     0 : 1
```

**Comment by fthomas** [comment]
:-)

**Pull request merged**
