### PR TITLE
try enable cross build

### PR DESCRIPTION
**Pull request by kailuowang**

### CODE REVIEW

**Comment by BennyHill** [comment]
The reason I originally pulled the crossbuild was in preparation for SBT 1.2 and the new crossProject that will use that. 

Maybe I'm premature in my assumption that will mean game over for older SBTs.

Up to you...we can always change again later. So LGTM....

**Comment by kailuowang** [comment]
@BennyHill I see. let's leave this one open to see if anyone complains about missing sbt0.13 release.

**Comment by BennyHill** [comment]
I've lost the reference, but IIRC composite projects are not backported to 0.13.x 

Also, just fyi, https://discuss.lightbend.com/t/spatial-representation-of-cross-building/1277

**Comment by kailuowang** [comment]
Closing this as this is too much cost for little benefits.

**Pull request closed without merging**
